---
# Main tasks file for fubarhouse.nodejs

- include_tasks: setup.yml

- name: "Set default ivm installation directory"
  set_fact:
    ivm_install_dir: "~/.ivm"
  when:
  - ivm_install_dir is not defined
  - install_ivm|bool == true

- name: "Set default nvm installation directory"
  set_fact:
    nvm_install_dir: "~/.nvm"
  when:
  - nvm_install_dir is not defined
  - install_nvm|bool == true

- include_tasks: nvm.yml
  when: install_nvm|bool == true

- include_tasks: ivm.yml
  when: install_ivm|bool == true

- include_tasks: nodejs.yml
  when: install_nodejs|bool == true

- include_tasks: iojs.yml
  when: install_iojs|bool == true

- include_tasks: npm.yml
  when: install_npm|bool == true
