---

- name: "NodeJS | Install dependencies (CentOS)"
  yum:
    name:
      - curl
      - gcc
      - git
      - findutils
      - make
      - rsync
      - tar
    state: installed
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution == "CentOS"

- name: "NodeJS | Install dependencies (Debian)"
  apt:
    name:
      - curl
      - gcc
      - git
      - findutils
      - make
      - rsync
      - tar
    state: installed
  when: ansible_os_family == "Debian"

- name: "NodeJS | Install dependencies (RedHat)"
  dnf:
    name:
      - curl
      - gcc
      - git
      - findutils
      - make
      - rsync
      - tar
    state: installed
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution != "CentOS"
